### ISSUE TITLE
how can i use this to generate first order markov chain number

### ISSUE THREAD

**Issue by jayjayram** [riotopsys/markov-chain#1]
I want to generate first order markov chain by giving randomly generated number sequence x=[5 6 1 6 4 1 2 4 6 6 1 6 6 3 5 1 3 6 5 6 4 1 6 6 5 5 5 3 4 2] as input. how to do this.

**Comment by riotopsys** [comment]
Please clarify, do you wish to use the command line interface or do you want to use the code inside another project.

If your using the CLI, build the jar and run this:

java -jar markov.jar < input.txt 

Where input.txt is your training strings (one pre line) and it will output until killed.
